language: node_js
node_js: stable

before_script: npm install
script: npm run test

jobs:
  include:
    - stage: npm release
      node_js: stable
      before_deploy:
      - npm install
      - npm run build
      deploy:
        skip_cleanup: true
        provider: npm
        email: "webdev@experium.ru"
        api_key: $NPM_API_KEY
        on:
          branch: master
